spring.cloud.stream:
  function:
    definition: evenNumberSquareProcessor
  bindings:
    evenNumberSquareProcessor-in-0:
      destination: numbers
      configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    evenNumberSquareProcessor-out-0:
      destination: squaredNumbers
  kafka:
    binder:
      brokers:
        - localhost:9091
        - localhost:9092

spring.kafka.properties:
  spring.json.trusted.packages: com.example.producer,com.example.models,com.example.processor,com.example.consumer
  default.deserialization.exception.handler: com.example.processor.CustomDeserializationExceptionHandler